# LIKE COMMENT

PUT http://localhost:3333/post/clups5pqn00022ym3j2aca76o/comment/clupsh5k900037ryty54a1zn2/like
content-type: application/json

{
    "authorId": ""
}

###

# REMOVE LIKE FROM COMMENT

PUT http://localhost:3333/post/clups5pqn00022ym3j2aca76o/comment/clupsh5k900037ryty54a1zn2/unlike
content-type: application/json

{
    "authorId": ""
}