# GET ALL POSTS

GET http://localhost:3333/posts

###

# GET POST BY ID

GET http://localhost:3333/post/clups5pqn00022ym3j2aca76o

###

# GET POSTS BY AUTHOR ID

GET http://localhost:3333/u/clups5b7n00002ym3ydnxjngs/posts

###

# CREATE POST

POST http://localhost:3333/post/create
content-type: application/json

{
    "title": "",
    "content": "",
    "authorId": ""
}

###

# UPDATE POST

PUT http://localhost:3333/post/clups5pqn00022ym3j2aca76o/update
content-type: application/json

{
    "title": "",
    "content": "",
    "authorId": ""
}

###

# DELETE POST

DELETE http://localhost:3333/post/cluprfeam0001zx8v8d730j5e/delete
content-type: application/json

{
    "authorId": ""
}